<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="factorial.fs" />
    <Compile Include="power.fs" />
    <Compile Include="first.fs" />
    <Compile Include="listreverse.fs" />
    <Compile Include="fibonacci.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FsUnit" Version="7.1.1" />
  </ItemGroup>

</Project>
