<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="BlockingQueue.fs" />
    <Compile Include="Diamond.fs" />
    <Compile Include="Supermap.fs" />
  </ItemGroup>

</Project>
